cookies:
    key: iwantobecomeseniordeveloper
#logging:
#    level:
#        org:
#            springframework:
#                security: DEBUG
server:
    port: 80
    servlet:
        context-path: /Shopme
spring:
    config:
        import: classpath:secret.yml
    application:
        name: ShopmeFrontEnd
    datasource:
        password: ${db.password}
        url: jdbc:mysql://localhost:3306/shopmedb
        username: ${db.username}
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true
        show-sql: false
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${oauth2.google.client-id}
                        client-secret: ${oauth2.google.client-secret}
                        scope:
                          - email
                          - profile
                    facebook:
                        client-id: ${oauth2.facebook.client-id}
                        client-secret: ${oauth2.facebook.client-secret}
                        scope:
                            - email
                            - public_profile
token:
    expires-after: 604800
